### ISSUE TITLE
SM-A310xx: Call is not received

### ISSUE THREAD

**Issue by derbabogamer** [vlourme/android#11]
Don't get calls

**Comment by vlourme** [comment]
Hi, is this a problem with sound (like ringtone not played when call happen) or RIL issue ?
Thanks for reporting

**Comment by logiczny** [comment]
This is propably phone.apk related - phone changing the GSM connection type when incoming call is made (ex. from LTE to H+), but showing absolutelly nothing on screen or not make any sound or vibrations. And didn't recieve any notification about missed calls or smth. Ghost-calls.

**Comment by vlourme** [comment]
Ok thanks for review!
I'll change **rild** and **cbd** to make work SIM detection back on some countries and i'll make my own tests. I'll link a testing build here soon.

**Comment by vlourme** [comment]
Update: submitted to a test.
Error is surely due to a bad RIL daemon handling, only CBD was managed and i forgot to put RILD handling in ramdisk.
https://github.com/vlourme/android_device_samsung_a3xeltexx/commit/e6df1129cd9e2a670807f712621ec0a40a2c501f

**Comment by vlourme** [comment]
**Fixed: all SER firmware was pulled to our vendor including libril.so that was missing**
